import { PanelModel } from '@syncfusion/ej2-angular-layouts';
import { panelData } from './model/panelModel';

export const lineData: any[] = [
  { x: 2013, y: 28 },
  { x: 2014, y: 25 },
  { x: 2015, y: 26 },
  { x: 2016, y: 27 },
  { x: 2017, y: 32 },
  { x: 2018, y: 35 },
];

export const piechart: any[] = [
  { x: 'TypeScript', y: 13, text: 'TS 13%' },
  { x: 'React', y: 12.5, text: 'Reat 12.5%' },
  { x: 'MVC', y: 12, text: 'MVC 12%' },
  { x: 'Core', y: 12.5, text: 'Core 12.5%' },
  { x: 'Vue', y: 10, text: 'Vue 10%' },
  { x: 'Angular', y: 40, text: 'Angular 40%' },
];

export const piechart1: any[] = [
  { x: 'Chrome', y: 37, text: '37%' },
  { x: 'UC Browser', y: 17, text: '17%' },
  { x: 'iPhone', y: 19, text: '19%' },
  { x: 'Others', y: 4, text: '4%' },
  { x: 'Opera', y: 11, text: '11%' },
  { x: 'Android', y: 12, text: '12%' },
];

export let barData: Object[] = [
  { x: 2006, y: 7.8 },
  { x: 2007, y: 7.2 },
  { x: 2008, y: 6.8 },
  { x: 2009, y: 10.7 },
  { x: 2010, y: 10.8 },
  { x: 2011, y: 9.8 },
];

export let data0: Object[] = [
  { x: 'Food', y: 90 },
  { x: 'Transport', y: 80 },
  { x: 'Medical', y: 50 },
  { x: 'Clothes', y: 70 },
  { x: 'Personal Care', y: 30 },
  { x: 'Books', y: 10 },
  { x: 'Fitness', y: 100 },
  { x: 'Electricity', y: 55 },
  { x: 'Tax', y: 20 },
  { x: 'Pet Care', y: 40 },
  { x: 'Education', y: 45 },
  { x: 'Entertainment', y: 75 },
];
export let data1: Object[] = [
  { x: 'Food', y: 40 },
  { x: 'Transport', y: 90 },
  { x: 'Medical', y: 80 },
  { x: 'Clothes', y: 30 },
  { x: 'Personal Care', y: 80 },
  { x: 'Books', y: 40 },
  { x: 'Fitness', y: 30 },
  { x: 'Electricity', y: 95 },
  { x: 'Tax', y: 50 },
  { x: 'Pet Care', y: 20 },
  { x: 'Education', y: 15 },
  { x: 'Entertainment', y: 45 },
];
export let data2: Object[] = [
  { x: 'Food', y: 70 },
  { x: 'Transport', y: 110 },
  { x: 'Medical', y: 120 },
  { x: 'Clothes', y: 60 },
  { x: 'Personal Care', y: 80 },
  { x: 'Books', y: 30 },
  { x: 'Fitness', y: 70 },
  { x: 'Electricity', y: 55 },
  { x: 'Tax', y: 40 },
  { x: 'Pet Care', y: 80 },
  { x: 'Education', y: 45 },
  { x: 'Entertainment', y: 65 },
];
export let data3: Object[] = [
  { x: 'Food', y: 120 },
  { x: 'Transport', y: 70 },
  { x: 'Medical', y: 50 },
  { x: 'Clothes', y: 180 },
  { x: 'Personal Care', y: 30 },
  { x: 'Books', y: 270 },
  { x: 'Fitness', y: 40 },
  { x: 'Electricity', y: 75 },
  { x: 'Tax', y: 65 },
  { x: 'Pet Care', y: 95 },
  { x: 'Education', y: 135 },
  { x: 'Entertainment', y: 115 },
];

export const sampleData: panelData[] = [
  {
    title: 'Bar',
    type: 'Bar',
    chartSetting: {
      dataSource: barData,
      xName: 'x',
      yName: 'y',
      xAxis: {
        valueType: 'Category',
      },
    },
    description: 'Bar Data',
    row: 0,
    col: 0,
  },
  {
    title: 'Line',
    type: 'Line',
    chartSetting: {
      dataSource: lineData,
      xName: 'x',
      yName: 'y',
      xAxis: {
        valueType: 'Category',
      },
    },
    description: 'Line Data',
    row: 0,
    col: 3,
  },

  {
    title: 'Pie',
    type: 'Pie',
    chartSetting: {
      dataSource: piechart1,
      xName: 'x',
      yName: 'y',
      xAxis: {
        valueType: 'Category',
      },
      innerRadius: '20%',
    },
    description: 'Pie Data',
    row: 1,
    col: 0,
  },
  {
    title: 'Pie 2',
    type: 'Pie',
    chartSetting: {
      dataSource: piechart,
      xName: 'x',
      yName: 'y',
      xAxis: {
        valueType: 'Category',
      },
      radius: '70%',
    },
    description: 'Pie Data',
    row: 1,
    col: 3,
  },

  {
    title: 'Multi Line',
    type: 'StackingLine',
    description: 'Pie Data',
    row: 2,
    col: 0,
    sizeX: 6,
    lineChartSetting: {
      xAxis: { interval: 1, valueType: 'Category' },
      yAxis: {
        title: 'Expense',
        interval: 100,
        labelFormat: '${value}',
      },
      lineData: [
        {
          dataSource: data0,
          xName: 'x',
          yName: 'y',
          name: 'Peter',
        },
        {
          dataSource: data1,
          xName: 'x',
          yName: 'y',
          name: 'Jon',
        },
        {
          dataSource: data2,
          xName: 'x',
          yName: 'y',
          name: 'Lance',
        },
        {
          dataSource: data3,
          xName: 'x',
          yName: 'y',
          name: 'Lim',
        },
      ],
    },
  },
];

export const somedummy = {
  title: 'Bar',
  type: 'Bar',
  chartSetting: {
    dataSource: barData,
    xName: 'x',
    yName: 'y',
    xAxis: {
      valueType: 'Category',
    },
  },
  description: 'Bar Data',
  row: 0,
  col: 0,
};

// this.primaryXAxis = {
//   interval: 1, valueType: 'Category'
// };
// this.primaryYAxis =
// {
//   title: 'Expense',
//   interval: 100,
//   labelFormat: '${value}',
// },

export const finalData: any[] = [
  {
      "Date": "2023-12-18",
      "Company Name": "Emerald Groves Co.",
      "Expense": 0,
      "Income": 310.00,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 1,
      "Account Number": "0987654321",
      "Transaction ID": 4321,
      "Transaction Zipcode": "54321",
      "Country": "Canada",
      "Time": "10:30 AM",
      "Bank Name": "Violet Banks"
  },
  {
      "Date": "2023-08-29",
      "Company Name": "Ocean Blue Innovations",
      "Expense": 150.00,
      "Income": 0,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 2,
      "Account Number": "7654321098",
      "Transaction ID": 2190,
      "Transaction Zipcode": "23456",
      "Country": "Germany",
      "Time": "1:45 PM",
      "Bank Name": "Cyan Bankers"
  },
  {
      "Date": "2023-03-30",
      "Company Name": "Ruby Skies Inc.",
      "Expense": 0,
      "Income": 220.00,
      "Month Name": "March",
      "Month Number": 3,
      "Vendor Type ID": 3,
      "Account Number": "2345678901",
      "Transaction ID": 1234,
      "Transaction Zipcode": "87654",
      "Country": "Australia",
      "Time": "11:00 AM",
      "Bank Name": "Golden Horizons"
  },
  {
      "Date": "2023-11-12",
      "Company Name": "Silver Fields Ltd.",
      "Expense": 120.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 4,
      "Account Number": "1098765432",
      "Transaction ID": 5678,
      "Transaction Zipcode": "98765",
      "Country": "France",
      "Time": "2:15 PM",
      "Bank Name": "Sapphire Bank"
  },
  {
      "Date": "2023-05-05",
      "Company Name": "Indigo Innovations Inc.",
      "Expense": 180.00,
      "Income": 0,
      "Month Name": "May",
      "Month Number": 5,
      "Vendor Type ID": 1,
      "Account Number": "0123456789",
      "Transaction ID": 2468,
      "Transaction Zipcode": "13579",
      "Country": "USA",
      "Time": "12:30 PM",
      "Bank Name": "Aqua Bankers"
  },
  {
      "Date": "2023-06-12",
      "Company Name": "Crimson Skies Co.",
      "Expense": 0,
      "Income": 230.00,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 2,
      "Account Number": "4567890123",
      "Transaction ID": 6789,
      "Transaction Zipcode": "34567",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Sapphire Horizons"
  },
  {
      "Date": "2023-03-25",
      "Company Name": "Emerald Innovations Inc.",
      "Expense": 190.00,
      "Income": 0,
      "Month Name": "March",
      "Month Number": 3,
      "Vendor Type ID": 3,
      "Account Number": "5678901234",
      "Transaction ID": 8901,
      "Transaction Zipcode": "45678",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Ruby Banks"
  },
  {
      "Date": "2023-10-08",
      "Company Name": "Azure Innovations Ltd.",
      "Expense": 0,
      "Income": 240.00,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 4,
      "Account Number": "6789012345",
      "Transaction ID": 9012,
      "Transaction Zipcode": "56789",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Crimson Bankers"
  },
  {
      "Date": "2023-07-19",
      "Company Name": "Golden Horizons Co.",
      "Expense": 220.00,
      "Income": 0,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 1,
      "Account Number": "7890123456",
      "Transaction ID": 1234,
      "Transaction Zipcode": "67890",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-12-01",
      "Company Name": "Violet Innovations Inc.",
      "Expense": 0,
      "Income": 250.00,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 2,
      "Account Number": "8901234567",
      "Transaction ID": 2345,
      "Transaction Zipcode": "78901",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Indigo Banks"
  },
  {
      "Date": "2023-04-14",
      "Company Name": "Crimson Innovations Ltd.",
      "Expense": 0,
      "Income": 260.00,
      "Month Name": "April",
      "Month Number": 4,
      "Vendor Type ID": 3,
      "Account Number": "0987654321",
      "Transaction ID": 5432,
      "Transaction Zipcode": "87654",
      "Country": "USA",
      "Time": "9:30 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-11-17",
      "Company Name": "Emerald Skies Innovations",
      "Expense": 230.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 4,
      "Account Number": "9876543210",
      "Transaction ID": 6789,
      "Transaction Zipcode": "76543",
      "Country": "UK",
      "Time": "10:45 AM",
      "Bank Name": "Golden Clouds"
  },
  {
      "Date": "2023-08-02",
      "Company Name": "Azure Innovations Inc.",
      "Expense": 0,
      "Income": 240.00,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 1,
      "Account Number": "2345678901",
      "Transaction ID": 8901,
      "Transaction Zipcode": "65432",
      "Country": "Canada",
      "Time": "11:15 AM",
      "Bank Name": "Ruby Banks"
  },
  {
      "Date": "2023-02-05",
      "Company Name": "Silver Horizons Ltd.",
      "Expense": 250.00,
      "Income": 0,
      "Month Name": "February",
      "Month Number": 2,
      "Vendor Type ID": 2,
      "Account Number": "3456789012",
      "Transaction ID": 4567,
      "Transaction Zipcode": "54321",
      "Country": "Germany",
      "Time": "1:00 PM",
      "Bank Name": "Sapphire Bankers"
  },
  {
      "Date": "2023-09-12",
      "Company Name": "Violet Innovations Ltd.",
      "Expense": 0,
      "Income": 270.00,
      "Month Name": "September",
      "Month Number": 9,
      "Vendor Type ID": 3,
      "Account Number": "4567890123",
      "Transaction ID": 6789,
      "Transaction Zipcode": "87654",
      "Country": "France",
      "Time": "2:30 PM",
      "Bank Name": "Emerald Horizons"
  },
  {
      "Date": "2023-06-22",
      "Company Name": "Golden Skies Innovations",
      "Expense": 260.00,
      "Income": 0,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 4,
      "Account Number": "5678901234",
      "Transaction ID": 7890,
      "Transaction Zipcode": "98765",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Azure Horizons"
  },
  {
      "Date": "2023-03-30",
      "Company Name": "Crimson Clouds Ltd.",
      "Expense": 0,
      "Income": 280.00,
      "Month Name": "March",
      "Month Number": 3,
      "Vendor Type ID": 1,
      "Account Number": "6789012345",
      "Transaction ID": 8901,
      "Transaction Zipcode": "12345",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Violet Banks"
  },
  {
      "Date": "2023-10-09",
      "Company Name": "Emerald Pathways Inc.",
      "Expense": 270.00,
      "Income": 0,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 2,
      "Account Number": "7890123456",
      "Transaction ID": 9012,
      "Transaction Zipcode": "23456",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Golden Horizons"
  },
  {
      "Date": "2023-07-16",
      "Company Name": "Azure Innovations Ltd.",
      "Expense": 0,
      "Income": 290.00,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 3,
      "Account Number": "8901234567",
      "Transaction ID": 1234,
      "Transaction Zipcode": "76543",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Silver Horizons"
  },
  {
      "Date": "2023-12-05",
      "Company Name": "Silver Clouds Innovations",
      "Expense": 280.00,
      "Income": 0,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 4,
      "Account Number": "0123456789",
      "Transaction ID": 2345,
      "Transaction Zipcode": "54321",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Crimson Banks"
  },
  {
      "Date": "2023-04-10",
      "Company Name": "Azure Horizons Ltd.",
      "Expense": 0,
      "Income": 300.00,
      "Month Name": "April",
      "Month Number": 4,
      "Vendor Type ID": 1,
      "Account Number": "2109876543",
      "Transaction ID": 4321,
      "Transaction Zipcode": "23456",
      "Country": "USA",
      "Time": "9:30 AM",
      "Bank Name": "Emerald Banks"
  },
  {
      "Date": "2023-11-21",
      "Company Name": "Violet Clouds Innovations",
      "Expense": 290.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 2,
      "Account Number": "3210987654",
      "Transaction ID": 9876,
      "Transaction Zipcode": "65432",
      "Country": "UK",
      "Time": "10:45 AM",
      "Bank Name": "Golden Horizons"
  },
  {
      "Date": "2023-08-04",
      "Company Name": "Golden Skies Ltd.",
      "Expense": 0,
      "Income": 310.00,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 3,
      "Account Number": "4321098765",
      "Transaction ID": 5432,
      "Transaction Zipcode": "76543",
      "Country": "Canada",
      "Time": "11:15 AM",
      "Bank Name": "Crimson Banks"
  },
  {
      "Date": "2023-02-07",
      "Company Name": "Silver Clouds Ltd.",
      "Expense": 320.00,
      "Income": 0,
      "Month Name": "February",
      "Month Number": 2,
      "Vendor Type ID": 4,
      "Account Number": "5432109876",
      "Transaction ID": 6789,
      "Transaction Zipcode": "87654",
      "Country": "Germany",
      "Time": "1:00 PM",
      "Bank Name": "Sapphire Horizons"
  },
  {
      "Date": "2023-09-14",
      "Company Name": "Emerald Innovations Ltd.",
      "Expense": 0,
      "Income": 330.00,
      "Month Name": "September",
      "Month Number": 9,
      "Vendor Type ID": 1,
      "Account Number": "6543210987",
      "Transaction ID": 8901,
      "Transaction Zipcode": "98765",
      "Country": "France",
      "Time": "2:30 PM",
      "Bank Name": "Ruby Banks"
  },
  {
      "Date": "2023-06-26",
      "Company Name": "Crimson Innovations Inc.",
      "Expense": 340.00,
      "Income": 0,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 2,
      "Account Number": "7654321098",
      "Transaction ID": 2345,
      "Transaction Zipcode": "87654",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Golden Clouds"
  },
  {
      "Date": "2023-03-26",
      "Company Name": "Azure Clouds Ltd.",
      "Expense": 0,
      "Income": 350.00,
      "Month Name": "March",
      "Month Number": 3,
      "Vendor Type ID": 3,
      "Account Number": "8765432109",
      "Transaction ID": 5432,
      "Transaction Zipcode": "76543",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Silver Horizons"
  },
  {
      "Date": "2023-10-11",
      "Company Name": "Violet Skies Innovations",
      "Expense": 360.00,
      "Income": 0,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 4,
      "Account Number": "9876543210",
      "Transaction ID": 8901,
      "Transaction Zipcode": "23456",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Azure Horizons"
  },
  {
      "Date": "2023-07-18",
      "Company Name": "Silver Innovations Ltd.",
      "Expense": 0,
      "Income": 370.00,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 1,
      "Account Number": "0987654321",
      "Transaction ID": 1234,
      "Transaction Zipcode": "98765",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Violet Banks"
  },
  {
      "Date": "2023-12-08",
      "Company Name": "Emerald Clouds Inc.",
      "Expense": 380.00,
      "Income": 0,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 2,
      "Account Number": "2109876543",
      "Transaction ID": 4567,
      "Transaction Zipcode": "87654",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Crimson Horizons"
  },
  {
      "Date": "2023-04-05",
      "Company Name": "Golden Pathways Ltd.",
      "Expense": 0,
      "Income": 400.00,
      "Month Name": "April",
      "Month Number": 4,
      "Vendor Type ID": 3,
      "Account Number": "1098765432",
      "Transaction ID": 5432,
      "Transaction Zipcode": "98765",
      "Country": "USA",
      "Time": "9:30 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-11-25",
      "Company Name": "Crimson Innovations Inc.",
      "Expense": 390.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 2,
      "Account Number": "2109876543",
      "Transaction ID": 8765,
      "Transaction Zipcode": "65432",
      "Country": "UK",
      "Time": "10:45 AM",
      "Bank Name": "Emerald Clouds"
  },
  {
      "Date": "2023-08-08",
      "Company Name": "Azure Innovations Ltd.",
      "Expense": 0,
      "Income": 420.00,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 1,
      "Account Number": "3210987654",
      "Transaction ID": 4321,
      "Transaction Zipcode": "76543",
      "Country": "Canada",
      "Time": "11:15 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-02-09",
      "Company Name": "Silver Skies Inc.",
      "Expense": 430.00,
      "Income": 0,
      "Month Name": "February",
      "Month Number": 2,
      "Vendor Type ID": 4,
      "Account Number": "4321098765",
      "Transaction ID": 9876,
      "Transaction Zipcode": "87654",
      "Country": "Germany",
      "Time": "1:00 PM",
      "Bank Name": "Golden Clouds"
  },
  {
      "Date": "2023-09-16",
      "Company Name": "Emerald Pathways Ltd.",
      "Expense": 0,
      "Income": 440.00,
      "Month Name": "September",
      "Month Number": 9,
      "Vendor Type ID": 3,
      "Account Number": "5432109876",
      "Transaction ID": 6789,
      "Transaction Zipcode": "98765",
      "Country": "France",
      "Time": "2:30 PM",
      "Bank Name": "Crimson Banks"
  },
  {
      "Date": "2023-06-28",
      "Company Name": "Crimson Clouds Ltd.",
      "Expense": 450.00,
      "Income": 0,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 2,
      "Account Number": "6543210987",
      "Transaction ID": 2345,
      "Transaction Zipcode": "87654",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-03-29",
      "Company Name": "Azure Horizons Inc.",
      "Expense": 0,
      "Income": 460.00,
      "Month Name": "March",
      "Month Number": 3,
      "Vendor Type ID": 1,
      "Account Number": "7654321098",
      "Transaction ID": 5432,
      "Transaction Zipcode": "76543",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Emerald Banks"
  },
  {
      "Date": "2023-10-19",
      "Company Name": "Violet Innovations Ltd.",
      "Expense": 470.00,
      "Income": 0,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 4,
      "Account Number": "8765432109",
      "Transaction ID": 8765,
      "Transaction Zipcode": "23456",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-07-23",
      "Company Name": "Silver Skies Ltd.",
      "Expense": 0,
      "Income": 480.00,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 3,
      "Account Number": "9876543210",
      "Transaction ID": 2345,
      "Transaction Zipcode": "98765",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Golden Banks"
  },
  {
      "Date": "2023-12-12",
      "Company Name": "Emerald Clouds Ltd.",
      "Expense": 490.00,
      "Income": 0,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 2,
      "Account Number": "1098765432",
      "Transaction ID": 6543,
      "Transaction Zipcode": "87654",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Crimson Horizons"
  },
  {
      "Date": "2023-05-01",
      "Company Name": "Golden Pathways Inc.",
      "Expense": 500.00,
      "Income": 0,
      "Month Name": "May",
      "Month Number": 5,
      "Vendor Type ID": 1,
      "Account Number": "2109876543",
      "Transaction ID": 7654,
      "Transaction Zipcode": "76543",
      "Country": "USA",
      "Time": "9:30 AM",
      "Bank Name": "Teal Clouds"
  },
  {
      "Date": "2023-01-25",
      "Company Name": "Violet Innovations Ltd.",
      "Expense": 0,
      "Income": 510.00,
      "Month Name": "January",
      "Month Number": 1,
      "Vendor Type ID": 4,
      "Account Number": "3210987654",
      "Transaction ID": 5432,
      "Transaction Zipcode": "98765",
      "Country": "UK",
      "Time": "10:45 AM",
      "Bank Name": "Emerald Horizons"
  },
  {
      "Date": "2023-08-15",
      "Company Name": "Azure Innovations Inc.",
      "Expense": 520.00,
      "Income": 0,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 3,
      "Account Number": "4321098765",
      "Transaction ID": 8765,
      "Transaction Zipcode": "65432",
      "Country": "Canada",
      "Time": "11:15 AM",
      "Bank Name": "Violet Banks"
  },
  {
      "Date": "2023-03-02",
      "Company Name": "Silver Innovations Ltd.",
      "Expense": 530.00,
      "Income": 0,
      "Month Name": "March",
      "Month Number": 3,
      "Vendor Type ID": 2,
      "Account Number": "5432109876",
      "Transaction ID": 2345,
      "Transaction Zipcode": "76543",
      "Country": "Germany",
      "Time": "1:00 PM",
      "Bank Name": "Golden Clouds"
  },
  {
      "Date": "2023-10-21",
      "Company Name": "Emerald Pathways Ltd.",
      "Expense": 540.00,
      "Income": 0,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 1,
      "Account Number": "6543210987",
      "Transaction ID": 7654,
      "Transaction Zipcode": "87654",
      "Country": "France",
      "Time": "2:30 PM",
      "Bank Name": "Crimson Horizons"
  },
  {
      "Date": "2023-06-30",
      "Company Name": "Crimson Clouds Ltd.",
      "Expense": 550.00,
      "Income": 0,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 4,
      "Account Number": "7654321098",
      "Transaction ID": 8765,
      "Transaction Zipcode": "23456",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-02-12",
      "Company Name": "Azure Innovations Inc.",
      "Expense": 560.00,
      "Income": 0,
      "Month Name": "February",
      "Month Number": 2,
      "Vendor Type ID": 3,
      "Account Number": "8765432109",
      "Transaction ID": 2345,
      "Transaction Zipcode": "98765",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Emerald Banks"
  },
  {
      "Date": "2023-11-29",
      "Company Name": "Violet Innovations Ltd.",
      "Expense": 570.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 2,
      "Account Number": "1098765432",
      "Transaction ID": 7654,
      "Transaction Zipcode": "76543",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-07-25",
      "Company Name": "Silver Skies Ltd.",
      "Expense": 580.00,
      "Income": 0,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 1,
      "Account Number": "2109876543",
      "Transaction ID": 3210,
      "Transaction Zipcode": "87654",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Golden Banks"
  },
  {
      "Date": "2023-12-15",
      "Company Name": "Emerald Clouds Ltd.",
      "Expense": 590.00,
      "Income": 0,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 4,
      "Account Number": "3210987654",
      "Transaction ID": 5432,
      "Transaction Zipcode": "98765",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Crimson Horizons"
  },
  {
      "Date": "2023-04-05",
      "Company Name": "Golden Pathways Ltd.",
      "Expense": 0,
      "Income": 4100.00,
      "Month Name": "April",
      "Month Number": 4,
      "Vendor Type ID": 3,
      "Account Number": "1098765432",
      "Transaction ID": 5432,
      "Transaction Zipcode": "98765",
      "Country": "USA",
      "Time": "9:30 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-11-25",
      "Company Name": "Crimson Innovations Inc.",
      "Expense": 3950.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 2,
      "Account Number": "2109876543",
      "Transaction ID": 8765,
      "Transaction Zipcode": "65432",
      "Country": "UK",
      "Time": "10:45 AM",
      "Bank Name": "Emerald Clouds"
  },
  {
      "Date": "2023-08-08",
      "Company Name": "Azure Innovations Ltd.",
      "Expense": 0,
      "Income": 4220.00,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 1,
      "Account Number": "3210987654",
      "Transaction ID": 4321,
      "Transaction Zipcode": "76543",
      "Country": "Canada",
      "Time": "11:15 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-02-09",
      "Company Name": "Silver Skies Inc.",
      "Expense": 4340.00,
      "Income": 0,
      "Month Name": "February",
      "Month Number": 2,
      "Vendor Type ID": 4,
      "Account Number": "4321098765",
      "Transaction ID": 9876,
      "Transaction Zipcode": "87654",
      "Country": "Germany",
      "Time": "1:00 PM",
      "Bank Name": "Golden Clouds"
  },
  {
      "Date": "2023-09-16",
      "Company Name": "Emerald Pathways Ltd.",
      "Expense": 0,
      "Income": 4450.00,
      "Month Name": "September",
      "Month Number": 9,
      "Vendor Type ID": 3,
      "Account Number": "5432109876",
      "Transaction ID": 6789,
      "Transaction Zipcode": "98765",
      "Country": "France",
      "Time": "2:30 PM",
      "Bank Name": "Crimson Banks"
  },
  {
      "Date": "2023-06-28",
      "Company Name": "Crimson Clouds Ltd.",
      "Expense": 4550.00,
      "Income": 0,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 2,
      "Account Number": "6543210987",
      "Transaction ID": 2345,
      "Transaction Zipcode": "87654",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-03-29",
      "Company Name": "Azure Horizons Inc.",
      "Expense": 0,
      "Income": 4600.00,
      "Month Name": "March",
      "Month Number": 3,
      "Vendor Type ID": 1,
      "Account Number": "7654321098",
      "Transaction ID": 5432,
      "Transaction Zipcode": "76543",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Emerald Banks"
  },
  {
      "Date": "2023-10-19",
      "Company Name": "Violet Innovations Ltd.",
      "Expense": 4750.00,
      "Income": 0,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 4,
      "Account Number": "8765432109",
      "Transaction ID": 8765,
      "Transaction Zipcode": "23456",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-07-23",
      "Company Name": "Silver Skies Ltd.",
      "Expense": 0,
      "Income": 4800.00,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 3,
      "Account Number": "9876543210",
      "Transaction ID": 2345,
      "Transaction Zipcode": "98765",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Golden Banks"
  },
  {
      "Date": "2023-12-12",
      "Company Name": "Emerald Clouds Ltd.",
      "Expense": 4900.00,
      "Income": 0,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 2,
      "Account Number": "1098765432",
      "Transaction ID": 6543,
      "Transaction Zipcode": "87654",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Crimson Horizons"
  },
  {
      "Date": "2023-04-05",
      "Company Name": "Golden Pathways Ltd.",
      "Expense": 0,
      "Income": 7100.00,
      "Month Name": "April",
      "Month Number": 4,
      "Vendor Type ID": 3,
      "Account Number": "1098765432",
      "Transaction ID": 5432,
      "Transaction Zipcode": "98765",
      "Country": "USA",
      "Time": "9:30 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-11-25",
      "Company Name": "Crimson Innovations Inc.",
      "Expense": 8950.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 2,
      "Account Number": "2109876543",
      "Transaction ID": 8765,
      "Transaction Zipcode": "65432",
      "Country": "UK",
      "Time": "10:45 AM",
      "Bank Name": "Emerald Clouds"
  },
  {
      "Date": "2023-08-08",
      "Company Name": "Azure Innovations Ltd.",
      "Expense": 0,
      "Income": 10220.00,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 1,
      "Account Number": "3210987654",
      "Transaction ID": 4321,
      "Transaction Zipcode": "76543",
      "Country": "Canada",
      "Time": "11:15 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-02-09",
      "Company Name": "Silver Skies Inc.",
      "Expense": 14340.00,
      "Income": 0,
      "Month Name": "February",
      "Month Number": 2,
      "Vendor Type ID": 4,
      "Account Number": "4321098765",
      "Transaction ID": 9876,
      "Transaction Zipcode": "87654",
      "Country": "Germany",
      "Time": "1:00 PM",
      "Bank Name": "Golden Clouds"
  },
  {
      "Date": "2023-09-16",
      "Company Name": "Emerald Pathways Ltd.",
      "Expense": 0,
      "Income": 26450.00,
      "Month Name": "September",
      "Month Number": 9,
      "Vendor Type ID": 3,
      "Account Number": "5432109876",
      "Transaction ID": 6789,
      "Transaction Zipcode": "98765",
      "Country": "France",
      "Time": "2:30 PM",
      "Bank Name": "Crimson Banks"
  },
  {
      "Date": "2023-06-28",
      "Company Name": "Crimson Clouds Ltd.",
      "Expense": 14550.00,
      "Income": 0,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 2,
      "Account Number": "6543210987",
      "Transaction ID": 2345,
      "Transaction Zipcode": "87654",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-03-29",
      "Company Name": "Azure Horizons Inc.",
      "Expense": 0,
      "Income": 17400.00,
      "Month Name": "March",
      "Month Number": 3,
      "Vendor Type ID": 1,
      "Account Number": "7654321098",
      "Transaction ID": 5432,
      "Transaction Zipcode": "76543",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Emerald Banks"
  },
  {
      "Date": "2023-10-19",
      "Company Name": "Violet Innovations Ltd.",
      "Expense": 23750.00,
      "Income": 0,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 4,
      "Account Number": "8765432109",
      "Transaction ID": 8765,
      "Transaction Zipcode": "23456",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-07-23",
      "Company Name": "Silver Skies Ltd.",
      "Expense": 0,
      "Income": 24800.00,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 3,
      "Account Number": "9876543210",
      "Transaction ID": 2345,
      "Transaction Zipcode": "98765",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Golden Banks"
  },
  {
      "Date": "2023-12-12",
      "Company Name": "Emerald Clouds Ltd.",
      "Expense": 29900.00,
      "Income": 0,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 2,
      "Account Number": "1098765432",
      "Transaction ID": 6543,
      "Transaction Zipcode": "87654",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Crimson Horizons"
  },
  {
      "Date": "2023-04-05",
      "Company Name": "Golden Pathways Ltd.",
      "Expense": 0,
      "Income": 2200.00,
      "Month Name": "April",
      "Month Number": 4,
      "Vendor Type ID": 3,
      "Account Number": "1098765432",
      "Transaction ID": 5432,
      "Transaction Zipcode": "98765",
      "Country": "USA",
      "Time": "9:30 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-11-25",
      "Company Name": "Crimson Innovations Inc.",
      "Expense": 3500.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 2,
      "Account Number": "2109876543",
      "Transaction ID": 8765,
      "Transaction Zipcode": "65432",
      "Country": "UK",
      "Time": "10:45 AM",
      "Bank Name": "Emerald Clouds"
  },
  {
      "Date": "2023-08-08",
      "Company Name": "Azure Innovations Ltd.",
      "Expense": 0,
      "Income": 2800.00,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 1,
      "Account Number": "3210987654",
      "Transaction ID": 4321,
      "Transaction Zipcode": "76543",
      "Country": "Canada",
      "Time": "11:15 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-02-09",
      "Company Name": "Silver Skies Inc.",
      "Expense": 4200.00,
      "Income": 0,
      "Month Name": "February",
      "Month Number": 2,
      "Vendor Type ID": 4,
      "Account Number": "4321098765",
      "Transaction ID": 9876,
      "Transaction Zipcode": "87654",
      "Country": "Germany",
      "Time": "1:00 PM",
      "Bank Name": "Golden Clouds"
  },
  {
      "Date": "2023-09-16",
      "Company Name": "Emerald Pathways Ltd.",
      "Expense": 0,
      "Income": 4500.00,
      "Month Name": "September",
      "Month Number": 9,
      "Vendor Type ID": 3,
      "Account Number": "5432109876",
      "Transaction ID": 6789,
      "Transaction Zipcode": "98765",
      "Country": "France",
      "Time": "2:30 PM",
      "Bank Name": "Crimson Banks"
  },
  {
      "Date": "2023-06-28",
      "Company Name": "Crimson Clouds Ltd.",
      "Expense": 4700.00,
      "Income": 0,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 2,
      "Account Number": "6543210987",
      "Transaction ID": 2345,
      "Transaction Zipcode": "87654",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-03-29",
      "Company Name": "Azure Horizons Inc.",
      "Expense": 0,
      "Income": 2000.00,
      "Month Name": "March",
      "Month Number": 3,
      "Vendor Type ID": 1,
      "Account Number": "7654321098",
      "Transaction ID": 5432,
      "Transaction Zipcode": "76543",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Emerald Banks"
  },
  {
      "Date": "2023-10-19",
      "Company Name": "Violet Innovations Ltd.",
      "Expense": 3000.00,
      "Income": 0,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 4,
      "Account Number": "8765432109",
      "Transaction ID": 8765,
      "Transaction Zipcode": "23456",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-07-23",
      "Company Name": "Silver Skies Ltd.",
      "Expense": 0,
      "Income": 4900.00,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 3,
      "Account Number": "9876543210",
      "Transaction ID": 2345,
      "Transaction Zipcode": "98765",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Golden Banks"
  },
  {
      "Date": "2023-12-12",
      "Company Name": "Emerald Clouds Ltd.",
      "Expense": 5000.00,
      "Income": 0,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 2,
      "Account Number": "1098765432",
      "Transaction ID": 6543,
      "Transaction Zipcode": "87654",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Crimson Horizons"
  },
  {
      "Date": "2023-05-15",
      "Company Name": "Golden Innovations Ltd.",
      "Expense": 0,
      "Income": 2500.00,
      "Month Name": "May",
      "Month Number": 5,
      "Vendor Type ID": 3,
      "Account Number": "1098765432",
      "Transaction ID": 5432,
      "Transaction Zipcode": "98765",
      "Country": "USA",
      "Time": "9:30 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-11-11",
      "Company Name": "Crimson Ventures Inc.",
      "Expense": 3200.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 2,
      "Account Number": "2109876543",
      "Transaction ID": 8765,
      "Transaction Zipcode": "65432",
      "Country": "UK",
      "Time": "10:45 AM",
      "Bank Name": "Emerald Clouds"
  },
  {
      "Date": "2023-08-28",
      "Company Name": "Azure Skies Ltd.",
      "Expense": 0,
      "Income": 2700.00,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 1,
      "Account Number": "3210987654",
      "Transaction ID": 4321,
      "Transaction Zipcode": "76543",
      "Country": "Canada",
      "Time": "11:15 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-02-20",
      "Company Name": "Silver Innovations Inc.",
      "Expense": 4200.00,
      "Income": 0,
      "Month Name": "February",
      "Month Number": 2,
      "Vendor Type ID": 4,
      "Account Number": "4321098765",
      "Transaction ID": 9876,
      "Transaction Zipcode": "87654",
      "Country": "Germany",
      "Time": "1:00 PM",
      "Bank Name": "Golden Clouds"
  },
  {
      "Date": "2023-09-28",
      "Company Name": "Emerald Ventures Ltd.",
      "Expense": 0,
      "Income": 4900.00,
      "Month Name": "September",
      "Month Number": 9,
      "Vendor Type ID": 3,
      "Account Number": "5432109876",
      "Transaction ID": 6789,
      "Transaction Zipcode": "98765",
      "Country": "France",
      "Time": "2:30 PM",
      "Bank Name": "Crimson Banks"
  },
  {
      "Date": "2023-06-10",
      "Company Name": "Crimson Skies Ltd.",
      "Expense": 4700.00,
      "Income": 0,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 2,
      "Account Number": "6543210987",
      "Transaction ID": 2345,
      "Transaction Zipcode": "87654",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-04-02",
      "Company Name": "Azure Clouds Inc.",
      "Expense": 0,
      "Income": 2100.00,
      "Month Name": "April",
      "Month Number": 4,
      "Vendor Type ID": 1,
      "Account Number": "7654321098",
      "Transaction ID": 5432,
      "Transaction Zipcode": "76543",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Emerald Banks"
  },
  {
      "Date": "2023-10-10",
      "Company Name": "Violet Ventures Ltd.",
      "Expense": 2500.00,
      "Income": 0,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 4,
      "Account Number": "8765432109",
      "Transaction ID": 8765,
      "Transaction Zipcode": "23456",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-07-05",
      "Company Name": "Silver Pathways Ltd.",
      "Expense": 0,
      "Income": 4600.00,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 3,
      "Account Number": "9876543210",
      "Transaction ID": 2345,
      "Transaction Zipcode": "98765",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Golden Banks"
  },
  {
      "Date": "2023-12-31",
      "Company Name": "Emerald Innovations Ltd.",
      "Expense": 5000.00,
      "Income": 0,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 2,
      "Account Number": "1098765432",
      "Transaction ID": 6543,
      "Transaction Zipcode": "87654",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Crimson Horizons"
  },
  {
      "Date": "2023-05-20",
      "Company Name": "Golden Streams Ltd.",
      "Expense": 200.00,
      "Income": 0,
      "Month Name": "May",
      "Month Number": 5,
      "Vendor Type ID": 3,
      "Account Number": "1098765432",
      "Transaction ID": 5432,
      "Transaction Zipcode": "98765",
      "Country": "USA",
      "Time": "9:30 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-11-18",
      "Company Name": "Crimson Circuits Inc.",
      "Expense": 300.00,
      "Income": 0,
      "Month Name": "November",
      "Month Number": 11,
      "Vendor Type ID": 2,
      "Account Number": "2109876543",
      "Transaction ID": 8765,
      "Transaction Zipcode": "65432",
      "Country": "UK",
      "Time": "10:45 AM",
      "Bank Name": "Emerald Clouds"
  },
  {
      "Date": "2023-08-15",
      "Company Name": "Azure Dynamics Ltd.",
      "Expense": 0,
      "Income": 400.00,
      "Month Name": "August",
      "Month Number": 8,
      "Vendor Type ID": 1,
      "Account Number": "3210987654",
      "Transaction ID": 4321,
      "Transaction Zipcode": "76543",
      "Country": "Canada",
      "Time": "11:15 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-02-27",
      "Company Name": "Silver Solutions Inc.",
      "Expense": 0,
      "Income": 450.00,
      "Month Name": "February",
      "Month Number": 2,
      "Vendor Type ID": 4,
      "Account Number": "4321098765",
      "Transaction ID": 9876,
      "Transaction Zipcode": "87654",
      "Country": "Germany",
      "Time": "1:00 PM",
      "Bank Name": "Golden Clouds"
  },
  {
      "Date": "2023-09-10",
      "Company Name": "Emerald Circuits Ltd.",
      "Expense": 500.00,
      "Income": 0,
      "Month Name": "September",
      "Month Number": 9,
      "Vendor Type ID": 3,
      "Account Number": "5432109876",
      "Transaction ID": 6789,
      "Transaction Zipcode": "98765",
      "Country": "France",
      "Time": "2:30 PM",
      "Bank Name": "Crimson Banks"
  },
  {
      "Date": "2023-06-05",
      "Company Name": "Crimson Solutions Ltd.",
      "Expense": 0,
      "Income": 550.00,
      "Month Name": "June",
      "Month Number": 6,
      "Vendor Type ID": 2,
      "Account Number": "6543210987",
      "Transaction ID": 2345,
      "Transaction Zipcode": "87654",
      "Country": "USA",
      "Time": "9:00 AM",
      "Bank Name": "Teal Horizons"
  },
  {
      "Date": "2023-04-17",
      "Company Name": "Azure Streams Inc.",
      "Expense": 600.00,
      "Income": 0,
      "Month Name": "April",
      "Month Number": 4,
      "Vendor Type ID": 1,
      "Account Number": "7654321098",
      "Transaction ID": 5432,
      "Transaction Zipcode": "76543",
      "Country": "UK",
      "Time": "10:15 AM",
      "Bank Name": "Emerald Banks"
  },
  {
      "Date": "2023-10-29",
      "Company Name": "Violet Dynamics Ltd.",
      "Expense": 0,
      "Income": 650.00,
      "Month Name": "October",
      "Month Number": 10,
      "Vendor Type ID": 4,
      "Account Number": "8765432109",
      "Transaction ID": 8765,
      "Transaction Zipcode": "23456",
      "Country": "Canada",
      "Time": "11:30 AM",
      "Bank Name": "Violet Horizons"
  },
  {
      "Date": "2023-07-30",
      "Company Name": "Silver Circuits Ltd.",
      "Expense": 700.00,
      "Income": 0,
      "Month Name": "July",
      "Month Number": 7,
      "Vendor Type ID": 3,
      "Account Number": "9876543210",
      "Transaction ID": 2345,
      "Transaction Zipcode": "98765",
      "Country": "Germany",
      "Time": "12:45 PM",
      "Bank Name": "Golden Banks"
  },
  {
      "Date": "2023-12-05",
      "Company Name": "Emerald Dynamics Ltd.",
      "Expense": 0,
      "Income": 750.00,
      "Month Name": "December",
      "Month Number": 12,
      "Vendor Type ID": 2,
      "Account Number": "1098765432",
      "Transaction ID": 6543,
      "Transaction Zipcode": "87654",
      "Country": "France",
      "Time": "2:00 PM",
      "Bank Name": "Crimson Horizons"
  }
]
